### ISSUE TITLE
hostnames/URLs are not supported

### ISSUE THREAD

**Issue by edsiper** [pwhelan/gping#1]
If I try to ping a machine by using the hostname or a domain it get's stuck, e.g:

- gping localhost
- gping something.com

**Comment by pwhelan** [comment]
Oddly enough, it works for me:

![Screenshot 2023-05-26 at 09 44 36](https://github.com/pwhelan/gping/assets/601645/50962693-18fe-4ed2-a989-20fb498aaa2d)

Did it fail when executing it from docker?

*** edit ***

Docker also seems to work flawlessly for me on macos:

```bash
$ docker run -ti pwhelan/gping:latest www.google.com
```

![Screenshot 2023-05-26 at 11 48 53](https://github.com/pwhelan/gping/assets/601645/fe224c16-cc0d-4f9e-b4fc-0e5d7e8e57da)

**Comment by edsiper** [comment]
oh, it works now, something wrong with my network that day then. thanks
